
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:14 (project)"
    message: |
      The target system is: iOS - 12.0 - 
      The host system is: Darwin - 24.5.0 - arm64
...
