#.github/workflows/build_native_plugin.yml

name: Build Cross-Platform Phonemizer Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: Windows
            arch: x86_64
          - os: macos-latest
            target: macOS
            arch: x86_64
          - os: macos-latest
            target: macOS
            arch: arm64
          - os: ubuntu-latest
            target: Android
            arch: arm64-v8a
          - os: ubuntu-latest
            target: Android
            arch: armeabi-v7a
          - os: macos-latest
            target: iOS
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up MSVC for Windows
      if: matrix.target == 'Windows'
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Set up Android NDK
      if: matrix.target == 'Android'
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c

    - name: Set up Xcode for iOS
      if: matrix.target == 'iOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Install build tools for iOS
      if: matrix.target == 'iOS'
      run: |
        # Ensure command line tools are installed
        xcode-select --install || true
        # Accept Xcode license
        sudo xcodebuild -license accept || true

    - name: Configure CMake
      shell: bash
      run: |
        if [ "${{ matrix.target }}" == "Android" ]; then
          echo "Android NDK Home: $ANDROID_NDK_HOME"
          echo "Android ABI: ${{ matrix.arch }}"
          echo "Checking NDK installation:"
          if [ -d "$ANDROID_NDK_HOME" ]; then
            echo "NDK directory exists"
            # Check for prebuilt directory structure
            if [ -d "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt" ]; then
              echo "Available prebuilt directories:"
              ls -la "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/" 2>/dev/null || echo "Could not list prebuilt directories"
              # Try to find the correct prebuilt directory
              PREBUILT_DIR=$(find "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt" -maxdepth 1 -type d -name "*linux*" | head -1)
              if [ -n "$PREBUILT_DIR" ]; then
                echo "Using prebuilt directory: $PREBUILT_DIR"
                echo "Sample toolchain files:"
                ls -la "$PREBUILT_DIR/bin/" 2>/dev/null | head -3 || echo "Could not list toolchain files"
              fi
            fi
          else
            echo "NDK directory not found!"
          fi
        fi
        
        if [ "${{ matrix.target }}" == "iOS" ]; then
          # iOS requires special handling with proper Xcode toolchain
          export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
          export iOS_PLATFORM=OS
          export iOS_SDK_VERSION=$(xcrun --show-sdk-version --sdk iphoneos)
          
          echo "iOS build environment:"
          echo "DEVELOPER_DIR: $DEVELOPER_DIR"
          echo "iOS SDK Version: $iOS_SDK_VERSION"
          echo "iOS SDK Path: $(xcrun --show-sdk-path --sdk iphoneos)"
          echo "Available iOS SDKs: $(xcodebuild -showsdks | grep iOS)"
          echo "Current working directory: $(pwd)"
          echo "Checking for toolchain file:"
          ls -la cmake/ios.toolchain.cmake || echo "Toolchain file not found"
          
          # Verify Xcode installation
          if ! command -v xcodebuild &> /dev/null; then
            echo "ERROR: xcodebuild not found"
            exit 1
          fi
          
          # Configure with iOS toolchain using absolute path
          TOOLCHAIN_FILE="$(pwd)/cmake/ios.toolchain.cmake"
          echo "Using toolchain file: $TOOLCHAIN_FILE"
          
          if [ ! -f "$TOOLCHAIN_FILE" ]; then
            echo "ERROR: Toolchain file not found at $TOOLCHAIN_FILE"
            exit 1
          fi
          
          cmake -B build -G Xcode -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" \
            -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM="" \
            -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED=NO \
            -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO \
            -DBUILD_SHARED_LIBS=OFF
        else
          echo "Configuring CMake for ${{ matrix.target }} ${{ matrix.arch }}"
          
          if [ "${{ matrix.target }}" == "Android" ]; then
            echo "Android-specific configuration:"
            echo "ANDROID_NDK_HOME: $ANDROID_NDK_HOME"
            echo "Using toolchain: $ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake"
            echo "Target ABI: ${{ matrix.arch }}"
            echo "Platform: android-21"
          fi
          
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            ${{ matrix.target == 'Android' && format('-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI={0} -DANDROID_PLATFORM=android-21', matrix.arch) || '' }} \
            ${{ matrix.target == 'macOS' && format('-DCMAKE_OSX_ARCHITECTURES={0}', matrix.arch) || '' }}
        fi

    - name: Build with CMake
      shell: bash
      run: |
        if [ "${{ matrix.target }}" == "iOS" ]; then
          # For iOS, use Xcode build system with verbose output
          echo "Building for iOS with Xcode..."
          cmake --build build --config Release --verbose -- -allowProvisioningUpdates
          
          # Check if the library was built successfully
          if [ -f "build/Release-iphoneos/libpiper_phonemize.a" ]; then
            echo "iOS library built successfully"
            ls -la build/Release-iphoneos/libpiper_phonemize.a
          else
            echo "iOS library not found, checking other locations..."
            find build -name "libpiper_phonemize*" -type f
          fi
        else
          # Standard build for other platforms
          cmake --build build --config Release
        fi
      continue-on-error: ${{ matrix.target == 'iOS' }}

    - name: Prepare Artifacts
      shell: bash
      run: |
        mkdir -p artifacts/Plugins/${{ matrix.target }}/${{ matrix.arch }}
        mkdir -p artifacts/StreamingAssets/espeak-ng-data

        # Copy compiled library
        if [ "${{ matrix.target }}" == "Windows" ]; then
          cp build/Release/piper_phonemize.dll artifacts/Plugins/Windows/x86_64/ || cp build/piper_phonemize.dll artifacts/Plugins/Windows/x86_64/ || true
        elif [ "${{ matrix.target }}" == "macOS" ]; then
          cp build/libpiper_phonemize.dylib artifacts/Plugins/macOS/${{ matrix.arch }}/ || true
        elif [ "${{ matrix.target }}" == "Android" ]; then
          cp build/libpiper_phonemize.so artifacts/Plugins/Android/${{ matrix.arch }}/ || true
        elif [ "${{ matrix.target }}" == "iOS" ]; then
          # Check multiple possible locations for iOS library
          if [ -f "build/Release-iphoneos/libpiper_phonemize.a" ]; then
            cp build/Release-iphoneos/libpiper_phonemize.a artifacts/Plugins/iOS/ || true
          elif [ -f "build/libpiper_phonemize.a" ]; then
            cp build/libpiper_phonemize.a artifacts/Plugins/iOS/ || true
          else
            echo "iOS library not found, checking all locations..."
            find build -name "libpiper_phonemize*" -type f || true
          fi
        fi

        # Copy espeak-ng data (adjust path based on actual build structure)
        if [ -d "build/ei/share/espeak-ng-data" ]; then
          cp -r build/ei/share/espeak-ng-data/* artifacts/StreamingAssets/espeak-ng-data/ || true
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: phonemizer-plugin-${{ matrix.target }}-${{ matrix.arch }}
        path: artifacts/