#.github/workflows/build_native_plugin.yml

name: Build Cross-Platform Phonemizer Plugin

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: Windows
            arch: x86_64
          - os: macos-latest
            target: macOS
            arch: x86_64
          - os: macos-latest
            target: macOS
            arch: arm64
          - os: ubuntu-latest
            target: Android
            arch: arm64-v8a
          - os: ubuntu-latest
            target: Android
            arch: armeabi-v7a
          - os: macos-latest
            target: iOS
            arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up MSVC for Windows
      if: matrix.target == 'Windows'
      uses: TheMrMilchmann/setup-msvc-dev@v3
      with:
        arch: x64

    - name: Set up Android NDK
      if: matrix.target == 'Android'
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r23c

    - name: Configure CMake
      run: |
        if [ "${{ matrix.target }}" == "Android" ]; then
          echo "Android NDK Home: $ANDROID_NDK_HOME"
          echo "Android ABI: ${{ matrix.arch }}"
          echo "Checking NDK toolchain:"
          ls -la $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/ | head -5
        fi
        
        if [ "${{ matrix.target }}" == "iOS" ]; then
          # iOS requires special handling
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake || \
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0
        else
          cmake -B build -DCMAKE_BUILD_TYPE=Release \
            ${{ matrix.target == 'Android' && format('-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake -DANDROID_ABI={0} -DANDROID_PLATFORM=21', matrix.arch) || '' }} \
            ${{ matrix.target == 'macOS' && format('-DCMAKE_OSX_ARCHITECTURES={0}', matrix.arch) || '' }}
        fi

    - name: Build with CMake
      run: cmake --build build --config Release
      continue-on-error: ${{ matrix.target == 'iOS' }}

    - name: Prepare Artifacts
      run: |
        mkdir -p artifacts/Plugins/${{ matrix.target }}/${{ matrix.arch }}
        mkdir -p artifacts/StreamingAssets/espeak-ng-data

        # Copy compiled library
        if [ "${{ matrix.target }}" == "Windows" ]; then
          cp build/Release/piper_phonemize.dll artifacts/Plugins/Windows/x86_64/ || cp build/piper_phonemize.dll artifacts/Plugins/Windows/x86_64/ || true
        elif [ "${{ matrix.target }}" == "macOS" ]; then
          cp build/libpiper_phonemize.dylib artifacts/Plugins/macOS/${{ matrix.arch }}/ || true
        elif [ "${{ matrix.target }}" == "Android" ]; then
          cp build/libpiper_phonemize.so artifacts/Plugins/Android/${{ matrix.arch }}/ || true
        elif [ "${{ matrix.target }}" == "iOS" ]; then
          cp build/libpiper_phonemize.a artifacts/Plugins/iOS/ || true
        fi

        # Copy espeak-ng data (adjust path based on actual build structure)
        if [ -d "build/ei/share/espeak-ng-data" ]; then
          cp -r build/ei/share/espeak-ng-data/* artifacts/StreamingAssets/espeak-ng-data/ || true
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: phonemizer-plugin-${{ matrix.target }}-${{ matrix.arch }}
        path: artifacts/